name: linux

on:
  push:
    branches: [ main ]
    paths:
      - 'linux'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: ./install-deps.sh
      
      - name: download linux repository
        run: wget https://github.com/0601p/linux/archive/${GITHUB_REF#refs/heads/}.zip

      - name: unzip linux repository
        run: unzip ${GITHUB_REF#refs/heads/}.zip
        
      - name: build linux
        run: ./build-linux.sh ${GITHUB_REF#refs/heads/} tinyconfig
