name: test

on:
  push:
    branches: [ main ]
    paths:
      - 'test/**'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: compile
        run: make -C test
        
